# Each day during signups, after you post a signup post, copy its 6-character ID to this array.
signupPageSubmissionIds = ['mww6s3', 'mxj2e9', 'mz5drb', 'mzo5y4', 'n0dle0', 'n13gai', 'n1ud2c']
signupPageFlaskPort = 8917
challengePageSubmissionId = 'n2j2g9'
challengePageFlaskPort = 8916
thisMonthName = "May"
nextMonthName = "June"
readAllCommentsWhichCanBeSlower = False
currentMonthTotalDays = 31
previousMonthTotalDays = 30
previousMonthURL = "https://www.reddit.com/r/pornfree/comments/mhuw7k/stay_clean_april_this_thread_updated_daily_check/"
nextMonthURL = "https://www.reddit.com/r/pornfree/comments/nptos1/stay_clean_june_this_thread_updated_daily_check/"

participantFileNames = ['../stayclean-2014-november/participants.txt',
                        '../stayclean-2014-december/participants.txt',
                        '../stayclean-2015-january/participants.txt',
                        '../stayclean-2015-february/participants.txt',
                        '../stayclean-2015-march/participants.txt',
                        '../stayclean-2015-april/participants.txt',
                        '../stayclean-2015-may/participants.txt',
                        '../stayclean-2015-june/participants.txt',
                        '../stayclean-2015-july/participants.txt',
                        '../stayclean-2015-august/participants.txt',
                        '../stayclean-2015-september/participants.txt',
                        '../stayclean-2015-october/participants.txt',
                        '../stayclean-2015-november/participants.txt',
                        '../stayclean-2015-december/participants.txt',
                        '../stayclean-2016-january/participants.txt',
                        '../stayclean-2016-february/participants.txt',
                        '../stayclean-2016-march/participants.txt',
                        '../stayclean-2016-april/participants.txt',
                        '../stayclean-2016-may/participants.txt',
                        '../stayclean-2016-june/participants.txt',
                        '../stayclean-2016-july/participants.txt',
                        '../stayclean-2016-august/participants.txt',
                        '../stayclean-2016-september/participants.txt',
                        '../stayclean-2016-october/participants.txt',
                        '../stayclean-2016-november/participants.txt',
                        '../stayclean-2016-december/participants.txt',
                        '../stayclean-2017-january/participants.txt',
                        '../stayclean-2017-february/participants.txt',
                        '../stayclean-2017-march/participants.txt',
                        '../stayclean-2017-april/participants.txt',
                        '../stayclean-2017-may/participants.txt',
                        '../stayclean-2017-june/participants.txt',
                        '../stayclean-2017-july/participants.txt',
                        '../stayclean-2017-august/participants.txt',
                        '../stayclean-2017-september/participants.txt',
                        '../stayclean-2017-october/participants.txt',
                        '../stayclean-2017-november/participants.txt',
                        '../stayclean-2017-december/participants.txt',
                        '../stayclean-2018-january/participants.txt',
                        '../stayclean-2018-february/participants.txt',
                        '../stayclean-2018-march/participants.txt',
                        '../stayclean-2018-april/participants.txt',
                        '../stayclean-2018-may/participants.txt',
                        '../stayclean-2018-june/participants.txt',
                        '../stayclean-2018-july/participants.txt',
                        '../stayclean-2018-august/participants.txt',
                        '../stayclean-2018-september/participants.txt',
                        '../stayclean-2018-october/participants.txt',
                        '../stayclean-2018-november/participants.txt',
                        '../stayclean-2018-december/participants.txt',
                        '../stayclean-2019-january/participants.txt',
                        '../stayclean-2019-february/participants.txt',
                        '../stayclean-2019-march/participants.txt',
                        '../stayclean-2019-april/participants.txt',
                        '../stayclean-2019-may/participants.txt',
                        '../stayclean-2019-june/participants.txt',
                        '../stayclean-2019-july/participants.txt',
                        '../stayclean-2019-august/participants.txt',
                        '../stayclean-2019-september/participants.txt',
                        '../stayclean-2019-october/participants.txt',
                        '../stayclean-2019-november/participants.txt',
                        '../stayclean-2019-december/participants.txt',
                        '../stayclean-2020-january/participants.txt',
                        '../stayclean-2020-february/participants.txt',
                        '../stayclean-2020-march/participants.txt',
                        '../stayclean-2020-april/participants.txt',
                        '../stayclean-2020-may/participants.txt',
                        '../stayclean-2020-june/participants.txt',
                        '../stayclean-2020-july/participants.txt',
                        '../stayclean-2020-august/participants.txt',
                        '../stayclean-2020-september/participants.txt',
                        '../stayclean-2020-october/participants.txt',
                        '../stayclean-2020-november/participants.txt',
                        '../stayclean-2020-december/participants.txt',
                        '../stayclean-2021-january/participants.txt',
                        '../stayclean-2021-february/participants.txt',
                        '../stayclean-2021-march/participants.txt',
                        '../stayclean-2021-april/participants.txt',
                        './participants.txt']
